### ISSUE TITLE
Building Swift Packages

### ISSUE THREAD

**Issue by Jomy10** [chinedufn/swift-bridge#35] opened 2022-03-03 13:20 UTC
I'll leave some of my thoughts here after writing that book chapter on how we should implement the build process for Swift packages into swift-bridge.

We'll probably want an extra option in build.rs to generate a Swift package, maybe something like:
```rust
swift_bridge_build::parse_bridges(bridges)
        .write_all_concatenated(out_dir, env!("CARGO_PKG_NAME"))
        .generate_package();
```

For generating the xcframework, we could either use the `xcodebuild` command, or we could write the `.plist` file manually, which I think could be a good option.

I think all of the other steps should be pretty straight forward, following the chapter of the book.

**Comment by chinedufn** [comment] 2022-03-03 14:12
Thanks for kicking this off.

So the final Swift Package needs to have the `.xcframework` file in it.

The `.xcframework` file contains the Rust libraries for each target that the user wants to support (i.e. one for iOS, one for MacOS, etc)

So.. we can't build the `.xcframework` until you've finished building your Rust libraries.

And the Swift Package depends on the `.xcframework`.

So.. it seems like we should build the `Swift Package` after we build all of our Rust code. 

Otherwise you end up with an incomplete Swift Package when you call `.generate_package()` in your example, so the user needs to know that they're supposed to then go create a `.xcframework`

---

What if we do all of the packaging in a single call?

First, we run our `build.rs` as usual. This will happen once per desired target (`aarch64-apple-ios`, `x86_64-apple-darwin`, etc)

```rust
// build.rs

swift_bridge_build::parse_bridges(bridges)
        .write_all_concatenated("some-out-dir", env!("CARGO_PKG_NAME"))
```

Then we run the CLI against that out dir. 

Maybe something along the lines of:

```
# In Bash
swift-bridge generate-package \
  --bridges-dir some-out-dir \
  --ios target/aarch64-apple-ios/debug/libmy_rust_lib.a \
  --macos target/x86_64-apple-darwin/debug/libmy_rust_lib.a \
  --out-dir ./my-swift-package
```

And the CLI would just call something like `swift_bridge_build::generate_package` to handle everything (calling `xcodebuild`, generating the `Package.swift` file, etc).

---

How does this approach sound? If it sounds good, I think a good starting place would be implementing something like `swift_bridge_build::generate_package(config: GeneratePackageConfig)` and landing that in a PR.

Then after that we would make the `swift-bridge-cli` use that generate package function.

**Comment by Jomy10** [comment] 2022-03-03 14:50
I just have one comment:

Are the target directories always the same for any rust project? Because in that case, I think it would be easier if we had something like
```bash
swift-bridge generate-package \
    --bridges-out some-out-dir \
    --platforms ios simulator macos \
    --out-dir ./my-swift-package
```
(or something similar)

Or we could have both options for flexibility.

---
I'll work on `swift_bridge_build::generate_package(config: GeneratePackageConfig)` in the next couple of days/weeks (whenever I have time). 

For `GeneratePackageConfig`, I think it should look something like this:
```rust
struct GeneratePackageConfig {
    bridge_dir: String,
    paths: HashMap<String, String>,
    out_dir: String
}
```

Where paths would look something like this (in rusty pseudo code):
```
[
    ("ios", "target/aarch64-apple-ios/debug/libmy_rust_lib.a"),
    ("macos", "target/x86_64-apple-darwin/debug/libmy_rust_lib.a")
]
```

Feel free to add anything to my current idea

**Comment by chinedufn** [comment] 2022-03-03 15:46
> Are the target directories always the same for any rust project?

They aren't. For example, you can use the `CARGO_TARGET_DIR=/path/to/target` environment variable to override it.

But even still, someone might not be using `Cargo` as their build system at all. They could just be using `rustc` directly, for example. In which case we'd have no way to know where their files are.

This is the sort of command that you set up once, and not a command that you manually type out a lot, so it's better that we avoid any magic and just keep things explicit. Easier to understand and more flexible.

> For GeneratePackageConfig, I think it should look something like this:

My understanding is that there are a finite number of Swift Package targets? (iOS, MacOS, Simulator, maybe a couple more?)

If so we shouldn't use a HashMap and can instead just enumerate the targets i.e.:

```rust
struct GeneratePackageConfig<'a> {
    bridge_dir: &'a dyn AsRef<Path>,
    ios_rust_lib: Option<&'a dyn AsRef<Path>>,
    macos_rust_lib: Option<&'a dyn AsRef<Path>>,
    simulator_rust_lib: Option<&'a dyn AsRef<Path>>,
    out_dir: &'a dyn AsRef<Path>
}
```

May also end up needing some other things like `name: String` for the name of the package, perhaps. Not sure, haven't thought about it.

> I'll work on swift_bridge_build::generate_package(config: GeneratePackageConfig) in the next couple of days/weeks (whenever I have time).

Awesome! Feel free to ask questions whenever you like!

**Comment by Jomy10** [comment] 2022-03-03 15:58
Alright, I've already been toying around a bit. A hashmap seems to be the most logical to me, because it can be looped over.

There are indeed a finite number of targets (iOS, macOS (x64 & arm), simulator, watchOS, tvOS and macCatalyst. I think that's all of them)

**Comment by chinedufn** [comment] 2022-03-03 16:17
Ok `HashMap` sounds good too. Would just use an enum for the key such as `enum AppleTarget {Ios, MacOs, /* .. etc .. */`.

**Comment by Jomy10** [comment] 2022-03-04 09:12
I have converted a Rust project to a package and I am currently getting the following error when trying to run a project depending on it:

```
Undefined symbols for architecture x86_64:
  "___swift_bridge__$SwiftString$_free", referenced from:
      __ZN92_$LT$swift_bridge..std_bridge..string..ffi..SwiftString$u20$as$u20$core..ops..drop..Drop$GT$4drop17h941b26836c26daf0E in libsample_project.a(swift_bridge-660b198e54141f98.swift_bridge.e62a51d3-cgu.11.rcgu.o)
  "___swift_bridge__$SwiftString$as_ptr", referenced from:
      __ZN12swift_bridge10std_bridge6string3ffi11SwiftString6as_ptr17h6d05e0114c96242bE in libsample_project.a(swift_bridge-660b198e54141f98.swift_bridge.e62a51d3-cgu.11.rcgu.o)
  "___swift_bridge__$SwiftString$len", referenced from:
      __ZN12swift_bridge10std_bridge6string3ffi11SwiftString3len17h32e91826b23ed894E in libsample_project.a(swift_bridge-660b198e54141f98.swift_bridge.e62a51d3-cgu.11.rcgu.o)
  "___swift_bridge__$SwiftString$new", referenced from:
      __ZN12swift_bridge10std_bridge6string3ffi11SwiftString3new17h36126888f1b5ca79E in libsample_project.a(swift_bridge-660b198e54141f98.swift_bridge.e62a51d3-cgu.11.rcgu.o)
  "___swift_bridge__$SwiftString$new_with_str", referenced from:
      __ZN12swift_bridge10std_bridge6string3ffi11SwiftString12new_with_str17hda694a1273695caaE in libsample_project.a(swift_bridge-660b198e54141f98.swift_bridge.e62a51d3-cgu.11.rcgu.o)
ld: symbol(s) not found for architecture x86_64
```

Could this be something to do with recent changes, or do you know what might be going wrong here? Or should I try to look further?

**Comment by chinedufn** [comment] 2022-03-04 10:18
Yeah that's related to https://github.com/chinedufn/swift-bridge/commit/0332dc94a629f70d6f8f0a8eed4dafe3bc469040

Are you using the latest master branch for both `swift-bridge-build` and `swift-bridge`? Looks like you have an old version somewhere or you're using an old `.c` header file that needs to be generated so that it no longer has `SwiftString` in it.

**Comment by Jomy10** [comment] 2022-03-04 11:56
My forked master branch is up to date with this repo. The branch I am working on is copied from the master branch. I'm using `swift-bridge-build` and `swift-bridge` from the same branch in my [test project](https://github.com/Jomy10/swift-bridge/blob/gen_swift_package/crates/swift-bridge-build/tests/sample_project/Cargo.toml).

I'm not sure where I messed up. I ran cargo tests and integration test, and both completed without errors.

**Comment by chinedufn** [comment] 2022-03-04 12:13
Gotcha. Can you comment with steps to reproduce this issue in your repo?

**Comment by Jomy10** [comment] 2022-03-04 13:31
Alright, so after cloning the repo (`git clone -b gen_swift_package https://github.com/Jomy10/swift-bridge.git`):

```bash
cd crates/swift-bridge-build/tests/sample_project
# Build the sample rust project for iOS, Simulator and macOS
./build.sh

cd ..
# Generate a Swift package containing XCFramework in sample_project/MySwiftPackage
cargo test gen_package

# Test the new package
cd test_package
swift run
```
This will generate the following output:
```
Undefined symbols for architecture x86_64:
  "___swift_bridge__$SwiftString$_free", referenced from:
      __ZN92_$LT$swift_bridge..std_bridge..string..ffi..SwiftString$u20$as$u20$core..ops..drop..Drop$GT$4drop17h941b26836c26daf0E in libsample_project.a(swift_bridge-660b198e54141f98.swift_bridge.e62a51d3-cgu.11.rcgu.o)
  "___swift_bridge__$SwiftString$as_ptr", referenced from:
      __ZN12swift_bridge10std_bridge6string3ffi11SwiftString6as_ptr17h6d05e0114c96242bE in libsample_project.a(swift_bridge-660b198e54141f98.swift_bridge.e62a51d3-cgu.11.rcgu.o)
  "___swift_bridge__$SwiftString$len", referenced from:
      __ZN12swift_bridge10std_bridge6string3ffi11SwiftString3len17h32e91826b23ed894E in libsample_project.a(swift_bridge-660b198e54141f98.swift_bridge.e62a51d3-cgu.11.rcgu.o)
  "___swift_bridge__$SwiftString$new", referenced from:
      __ZN12swift_bridge10std_bridge6string3ffi11SwiftString3new17h36126888f1b5ca79E in libsample_project.a(swift_bridge-660b198e54141f98.swift_bridge.e62a51d3-cgu.11.rcgu.o)
  "___swift_bridge__$SwiftString$new_with_str", referenced from:
      __ZN12swift_bridge10std_bridge6string3ffi11SwiftString12new_with_str17hda694a1273695caaE in libsample_project.a(swift_bridge-660b198e54141f98.swift_bridge.e62a51d3-cgu.11.rcgu.o)
ld: symbol(s) not found for architecture x86_64
```

What ist should output is `Hello Rust!`.

I ran `cargo clean` before testing out everything.

**Comment by chinedufn** [comment] 2022-03-04 13:40
These instructions didn't work for me.

Can you replace the hard coded `SWIFT_BRIDGE_OUT_DIR` path in `build.sh` with something like https://github.com/chinedufn/swift-bridge/blob/87475eca8889e2d6ce39095868643082b411b58d/examples/async-functions/build.sh#L3-L8

I replaced it myself locally but still ran into other building issues. Mind verifying that your instructions work, from scratch?

**Comment by Jomy10** [comment] 2022-03-04 14:20
Oh, hadn't noticed I was using an absolute path instead of a relative one.

I removed everything that is ignored using `.gitignore` and redid all of the steps. Looks like it wasn't working because the target directory was set to the root. I have fixed that now.

And that has solved the problem as well.

Slight update to the instructions in case you still want to try it:
```bash
cd crates/swift-bridge-build/tests/sample_project
# Build the sample rust project for iOS, Simulator and macOS
./build.sh

cd ..
# Generate a Swift package containing XCFramework in sample_project/MySwiftPackage
cargo test gen_package

# Test the new package
cd test_project
swift run
```

**Comment by chinedufn** [comment] 2022-03-10 23:06
#36 gives us the ability to build using the API, so I'm closing this out.

We'll also want a CLI command, but we can worry about that in a separate issue.

**Closed by chinedufn** 2022-03-10 23:06 UTC
